org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false

version=1.0.0
group=net.morthen
java_version=25

modrinth_id=VfoViaID
curseforge_id=1466308

# Common
minecraft_version=26.1.2

mod_id=resource_zoom
mod_name=Resource Zoom
mod_author=Morthen
mod_license=MIT
mod_description=Simple and Lightweight Zoom Mod for Fabric, Forge and Neoforge.

neoform=26.1.2-1
neoforge=26.1.2.71
fabric_api=0.155.2+26.1.2
fabric_loader=0.19.3
forge=64.1.0

# Additional stuff
sources_url=https://github.com/Morthen-Mods/Resource-Zoom
issues_url=https://github.com/Morthen-Mods/Resource-Zoom/issues